<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>歷史四大報</title>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.2.2/bootstrap.min.js"></script>
<?php if (getenv('GOOGLEANALYTICS_ACCOUNT')) { ?>
<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', <?= json_encode(getenv('GOOGLEANALYTICS_ACCOUNT')) ?>]);
_gaq.push(['_trackPageview']);

(function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
<?php } ?>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.2.2/css/bootstrap.css">
</head>
<body>
JSON API: <code>http://<?= $_SERVER['HTTP_HOST'] ?>/index/json</code>
<hr>
<?php if ($this->before) { ?>
<h3><?= date('Y/m/d', $this->before) ?> 之前頭條</h3>
<?php } ?>
<table class="table">
    <thead>
        <tr>
            <td>日期</td>
            <td>四大報頭條</td>
            <td>來源</td>
        </tr>
    </thead>
    <tbody>
    <?php $last_time = null; ?>
    <?php for ($i = 0; $i <= 60; $i ++) { ?>
    <?php $time = strtotime("0:0:0 -{$i}day", $this->before ?: time()); ?>
    <?php $data = null; ?>
    <?php if ($log = HeadLineLog::find($time)) { ?>
    <?php $data = json_decode($log->data); ?>
    <?php $last_time = $log->time ?>
    <?php } ?>
    <tr>
        <td><?= date('Y/m/d D', $time) ?></td>
        <td>
            <?php if ($data) { ?>
            <ol>
                <?php foreach ($data->headlines as $headline) { list($paper, $title) = $headline; ?>
                <li><?= $this->escape($paper) ?>: <?= $this->escape($title) ?></li>
                <?php } ?>
            </ol>
            <?php } ?>
        </td>
        <td>
            <?php if ($data) { ?>
            <a href="<?= $this->escape($data->link) ?>"><?= $this->escape($data->title) ?></a>
            <?php } ?>
        </td>
    <?php } ?>
    </tbody>
</table>
<?php if (!is_null($last_time)) { ?>
<a href="/?before=<?= date('Ymd', $last_time - 86400) ?>">瀏覽 <?= date('Y/m/d', $last_time) ?> 之前的頭條</a>
<?php } ?>
<a href="https://github.com/ronnywang/lagnews"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png" alt="Fork me on GitHub"></a>
